// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Valles Puig, Ramon

use tempoch_time_data::{EopPoint, UtcTaiSegment};

pub struct Sources<'a> {
    pub utc_tai_history_url: &'a str,
    pub delta_t_observed_url: &'a str,
    pub delta_t_predictions_url: &'a str,
    pub eop_finals_url: &'a str,
    pub pre_1961_tai_minus_utc_approx: f64,
}

pub struct Provenance<'a> {
    pub utc_tai_sha: &'a str,
    pub delta_t_observed_sha: &'a str,
    pub delta_t_predictions_sha: &'a str,
    pub eop_finals_sha: &'a str,
}

fn render_segments(segments: &[UtcTaiSegment]) -> String {
    let mut out = String::new();
    for (i, seg) in segments.iter().enumerate() {
        let end = match seg.end_mjd {
            None => "None".to_string(),
            Some(v) => format!("Some({v})"),
        };
        if i > 0 {
            out.push('\n');
        }
        out.push_str(&format!(
            "    UtcTaiSegment {{\n        start_mjd: {},\n        end_mjd: {},\n        base_seconds: {:.7},\n        reference_mjd: {:.1},\n        slope_seconds_per_day: {:.7},\n    }},",
            seg.start_mjd, end, seg.base_seconds, seg.reference_mjd, seg.slope_seconds_per_day,
        ));
    }
    out
}

/// Emit `pub(crate) const NAME: &str = "URL";` in the same shape `cargo fmt`
/// would produce (a line wrap is required when the single-line form would
/// exceed rustfmt's default 100-column limit).
fn format_url_const(name: &str, url: &str) -> String {
    let single = format!("pub(crate) const {name}: &str = \"{url}\";");
    if single.len() <= 100 {
        single
    } else {
        format!("pub(crate) const {name}: &str =\n    \"{url}\";")
    }
}

fn render_points(points: &[(f64, f64)]) -> String {
    let mut out = String::new();
    for (i, (mjd, dt)) in points.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        out.push_str(&format!("    ({mjd:.3}, {dt:.4}),"));
    }
    out
}

pub fn render_generated_module(
    utc_tai_segments: &[UtcTaiSegment],
    modern_delta_t_points: &[(f64, f64)],
    observed_end_mjd: f64,
    sources: &Sources<'_>,
    provenance: &Provenance<'_>,
) -> String {
    let utc_history_start = utc_tai_segments[0].start_mjd;
    let modern_delta_t_start = modern_delta_t_points[0].0;
    let modern_delta_t_end = modern_delta_t_points.last().unwrap().0;

    format!(
        "// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Valles Puig, Ramon
//
// @generated by tempoch-time-data-updater
// Do not edit this file manually.
//
// Provenance (run `cargo run -p tempoch-time-data-updater -- --check` to verify):
//   UTC-TAI history  SHA-256: {utc_tai_sha}
//   \u{0394}T observed      SHA-256: {delta_t_obs_sha}
//   \u{0394}T predictions   SHA-256: {delta_t_pred_sha}
//
// The modern \u{0394}T series is a *derived* product: observed USNO monthly points
// are concatenated with C0-adjusted prediction points.  The boundary MJD
// between observed and predicted data is MODERN_DELTA_T_OBSERVED_END_MJD.

#[derive(Debug, Clone, Copy, PartialEq)]
pub(crate) struct UtcTaiSegment {{
    pub start_mjd: i32,
    pub end_mjd: Option<i32>,
    pub base_seconds: f64,
    pub reference_mjd: f64,
    pub slope_seconds_per_day: f64,
}}

pub(crate) const PRE_1961_TAI_MINUS_UTC_APPROX: f64 = {pre_1961:.1};
{utc_tai_url_const}
{dt_obs_url_const}
{dt_pred_url_const}
pub(crate) const UTC_TAI_HISTORY_START_MJD: i32 = {utc_history_start};
pub(crate) const MODERN_DELTA_T_START_MJD: f64 = {modern_start:.3};
/// Last MJD with an *observed* (non-predicted) \u{0394}T value in [`MODERN_DELTA_T_POINTS`].
/// Points after this MJD are C0-adjusted USNO predictions, not confirmed observations.
pub(crate) const MODERN_DELTA_T_OBSERVED_END_MJD: f64 = {observed_end:.3};
pub(crate) const MODERN_DELTA_T_END_MJD: f64 = {modern_end:.3};

#[rustfmt::skip]
pub(crate) const UTC_TAI_SEGMENTS: [UtcTaiSegment; {n_segs}] = [
{segments}
];

#[rustfmt::skip]
pub(crate) const MODERN_DELTA_T_POINTS: [(f64, f64); {n_points}] = [
{points}
];
",
        utc_tai_sha = provenance.utc_tai_sha,
        delta_t_obs_sha = provenance.delta_t_observed_sha,
        delta_t_pred_sha = provenance.delta_t_predictions_sha,
        pre_1961 = sources.pre_1961_tai_minus_utc_approx,
        utc_tai_url_const = format_url_const("UTC_TAI_HISTORY_URL", sources.utc_tai_history_url),
        dt_obs_url_const = format_url_const("DELTA_T_OBSERVED_URL", sources.delta_t_observed_url),
        dt_pred_url_const =
            format_url_const("DELTA_T_PREDICTIONS_URL", sources.delta_t_predictions_url),
        utc_history_start = utc_history_start,
        modern_start = modern_delta_t_start,
        observed_end = observed_end_mjd,
        modern_end = modern_delta_t_end,
        n_segs = utc_tai_segments.len(),
        segments = render_segments(utc_tai_segments),
        n_points = modern_delta_t_points.len(),
        points = render_points(modern_delta_t_points),
    )
}

fn render_eop_points(points: &[EopPoint]) -> String {
    let fmt_opt = |value: Option<f64>, decimals: usize| match value {
        Some(v) => format!("Some({v:.precision$})", precision = decimals),
        None => "None".to_string(),
    };
    let mut out = String::new();
    for (i, p) in points.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        let lod = fmt_opt(p.lod_milliseconds, 4);
        let pm_x = fmt_opt(p.pm_xp_arcsec, 6);
        let pm_y = fmt_opt(p.pm_yp_arcsec, 6);
        let dx = fmt_opt(p.dx_milliarcsec, 3);
        let dy = fmt_opt(p.dy_milliarcsec, 3);
        out.push_str(&format!(
            "    EopPoint {{ mjd: {}, pm_observed: {}, ut1_observed: {}, nutation_observed: {}, pm_xp_arcsec: {}, pm_yp_arcsec: {}, ut1_minus_utc_seconds: {:.7}, lod_milliseconds: {}, dx_milliarcsec: {}, dy_milliarcsec: {} }},",
            p.mjd,
            p.pm_observed,
            p.ut1_observed,
            p.nutation_observed,
            pm_x,
            pm_y,
            p.ut1_minus_utc_seconds,
            lod,
            dx,
            dy,
        ));
    }
    out
}

pub fn render_eop_module(
    eop_points: &[EopPoint],
    sources: &Sources<'_>,
    provenance: &Provenance<'_>,
) -> String {
    let start_mjd = eop_points[0].mjd;
    let end_mjd = eop_points.last().unwrap().mjd;
    let observed_end_mjd = eop_points
        .iter()
        .rev()
        .find(|p| p.ut1_observed)
        .map(|p| p.mjd)
        .unwrap_or(start_mjd);

    format!(
        "// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Valles Puig, Ramon
//
// @generated by tempoch-time-data-updater
// Do not edit this file manually.

#![allow(clippy::approx_constant)]

// Provenance (run `cargo run -p tempoch-time-data-updater -- --check` to verify):
//   finals2000A.all  SHA-256: {eop_sha}
//
// Source: IERS Bulletin A + C04 combined file, daily Earth Orientation
// Parameters from {eop_url}.
//
// `ut1_observed` / `pm_observed` / `nutation_observed` reflect the IERS
// `I`/`P` flag columns; `true` means the value is from the observed Bulletin C04
// series, `false` means it comes from a Bulletin A prediction. Optional fields
// stay as `None` when the upstream row leaves them blank; the generator does
// not fabricate zero-valued PM, LOD, or nutation entries.

#[derive(Debug, Clone, Copy, PartialEq)]
pub(crate) struct EopPoint {{
    pub mjd: i32,
    pub pm_observed: bool,
    pub ut1_observed: bool,
    pub nutation_observed: bool,
    /// Polar-motion x component, seconds of arc.
    /// `None` when the upstream row leaves the field blank.
    pub pm_xp_arcsec: Option<f64>,
    /// Polar-motion y component, seconds of arc.
    /// `None` when the upstream row leaves the field blank.
    pub pm_yp_arcsec: Option<f64>,
    /// UT1 \u{2212} UTC (DUT1), seconds of time.
    pub ut1_minus_utc_seconds: f64,
    /// Length of day excess over 86400 SI seconds, milliseconds of time.
    /// `None` when the upstream row does not carry a LOD value.
    pub lod_milliseconds: Option<f64>,
    /// Celestial pole offset dX (IAU 2000A nutation), milliarcseconds.
    /// `None` when the upstream row leaves the field blank.
    pub dx_milliarcsec: Option<f64>,
    /// Celestial pole offset dY (IAU 2000A nutation), milliarcseconds.
    /// `None` when the upstream row leaves the field blank.
    pub dy_milliarcsec: Option<f64>,
}}

{eop_url_const}
pub(crate) const EOP_START_MJD: i32 = {start_mjd};
/// Last MJD with an *observed* UT1\u{2212}UTC value (IERS flag `I`).
pub(crate) const EOP_OBSERVED_END_MJD: i32 = {observed_end_mjd};
/// Last MJD present in the series (observed or predicted).
pub(crate) const EOP_END_MJD: i32 = {end_mjd};

#[rustfmt::skip]
pub(crate) static EOP_POINTS: [EopPoint; {n_points}] = [
{points}
];
",
        eop_sha = provenance.eop_finals_sha,
        eop_url = sources.eop_finals_url,
        eop_url_const = format_url_const("EOP_FINALS_URL", sources.eop_finals_url),
        start_mjd = start_mjd,
        observed_end_mjd = observed_end_mjd,
        end_mjd = end_mjd,
        n_points = eop_points.len(),
        points = render_eop_points(eop_points),
    )
}
