#ifndef TEMPOCH_FFI_H
#define TEMPOCH_FFI_H

/* Warning: this file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
/* QttyQuantity and UnitId definitions come from qtty_ffi.h */
#include "qtty_ffi.h"


// Status codes returned by tempoch-ffi functions.
//
// Callers must inspect this value before reading any output parameters.
//
// # ABI Contract
//
// Discriminant values are frozen; new variants may only be added at the end.
//
enum tempoch_status_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  // Operation completed successfully.
  TEMPOCH_STATUS_T_OK = 0,
  // A required output pointer was null.
  TEMPOCH_STATUS_T_NULL_POINTER = 1,
  // UTC conversion failed (date out of range or invalid).
  TEMPOCH_STATUS_T_UTC_CONVERSION_FAILED = 2,
  // The period is invalid (start > end).
  TEMPOCH_STATUS_T_INVALID_PERIOD = 3,
  // The two periods do not intersect.
  TEMPOCH_STATUS_T_NO_INTERSECTION = 4,
  // The provided scale ID is not a recognized `TempochScale` discriminant.
  TEMPOCH_STATUS_T_INVALID_SCALE_ID = 5,
  // The quantity's unit is not a time-compatible duration unit.
  TEMPOCH_STATUS_T_INVALID_DURATION_UNIT = 6,
  // A Rust panic was caught at the FFI boundary.
  //
  // This indicates a bug in the underlying library; the panic payload is
  // discarded.  Domain errors (`UtcConversionFailed`, `InvalidPeriod`, etc.)
  // are never reported via this variant.
  TEMPOCH_STATUS_T_INTERNAL_PANIC = 7,
  // A UT1 / ΔT conversion was requested for a date outside the compiled
  // ΔT data horizon.  The output value has not been written.
  TEMPOCH_STATUS_T_UT1_HORIZON_EXCEEDED = 8,
};
#ifndef __cplusplus
typedef int32_t tempoch_status_t;
#endif // __cplusplus

// A time period expressed in Modified Julian Date, suitable for C interop.
typedef struct tempoch_period_mjd_t {
  // Start of the period (MJD).
  double start_mjd;
  // End of the period (MJD).
  double end_mjd;
} tempoch_period_mjd_t;

// UTC date-time breakdown for C interop.
typedef struct tempoch_utc_t {
  // Calendar year (e.g. 2026).
  int32_t year;
  // Month of the year (1–12).
  uint8_t month;
  // Day of the month (1–31).
  uint8_t day;
  // Hour of the day (0–23).
  uint8_t hour;
  // Minute of the hour (0–59).
  uint8_t minute;
  // Second of the minute (0–60). `60` denotes a positive leap second.
  uint8_t second;
  // Sub-second component in nanoseconds (0–999_999_999).
  uint32_t nanosecond;
} tempoch_utc_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the tempoch-ffi ABI version (major*10000 + minor*100 + patch).
//
// Current version: 0.4.0 → 400
 uint32_t tempoch_ffi_version(void);

// Create a new MJD period. Returns `InvalidPeriod` if the endpoints are
// non-finite or `start_mjd > end_mjd`.
//
// # Safety
// `out` must be a valid, writable pointer to `TempochPeriodMjd`.

tempoch_status_t tempoch_period_mjd_new(double start_mjd,
                                        double end_mjd,
                                        struct tempoch_period_mjd_t *out);

// Compute the duration of a period in days (end − start).
 double tempoch_period_mjd_duration_days(struct tempoch_period_mjd_t period);

// Compute the duration of a period as a `QttyQuantity` in days.
 qtty_quantity_t tempoch_period_mjd_duration_qty(struct tempoch_period_mjd_t period);

// Compute the intersection of two MJD periods.
//
// Returns `InvalidPeriod` if either input period is malformed and
// `NoIntersection` if the periods do not overlap.
//
// # Safety
// `out` must be a valid, writable pointer to `TempochPeriodMjd`.

tempoch_status_t tempoch_period_mjd_intersection(struct tempoch_period_mjd_t a,
                                                 struct tempoch_period_mjd_t b,
                                                 struct tempoch_period_mjd_t *out);

// Free a `TempochPeriodMjd` array allocated by a tempoch-ffi function.
//
// Passing a null pointer is safe (no-op).
//
// # Safety
// `ptr` and `count` must have been returned by the same function call and
// must not be used after this call.
 void tempoch_period_mjd_free(struct tempoch_period_mjd_t *ptr, uintptr_t count);

// Create a Julian Date from a raw `double`.
 double tempoch_jd_new(double value);

// Return the J2000.0 epoch as a Julian Date (2451545.0).
 double tempoch_jd_j2000(void);

// Convert a Julian Date to a Modified Julian Date.
 double tempoch_jd_to_mjd(double jd);

// Create a Julian Date from a UTC date-time.
//
// # Safety
// `out` must be a valid, writable pointer to `double`.
 tempoch_status_t tempoch_jd_from_utc(struct tempoch_utc_t utc, double *out);

// Convert a Julian Date to a UTC breakdown.
//
// # Safety
// `out` must be a valid, writable pointer to `TempochUtc`.
 tempoch_status_t tempoch_jd_to_utc(double jd, struct tempoch_utc_t *out);

// Create a Modified Julian Date from a raw `double`.
 double tempoch_mjd_new(double value);

// Convert a Modified Julian Date to a Julian Date.
 double tempoch_mjd_to_jd(double mjd);

// Create a Modified Julian Date from a UTC date-time.
//
// # Safety
// `out` must be a valid, writable pointer to `double`.
 tempoch_status_t tempoch_mjd_from_utc(struct tempoch_utc_t utc, double *out);

// Convert a Modified Julian Date to a UTC breakdown.
//
// # Safety
// `out` must be a valid, writable pointer to `TempochUtc`.
 tempoch_status_t tempoch_mjd_to_utc(double mjd, struct tempoch_utc_t *out);

// Compute the difference between two Julian Dates in days (jd1 − jd2).
 double tempoch_jd_difference(double jd1, double jd2);

// Add a duration in days to a Julian Date.
 double tempoch_jd_add_days(double jd, double days);

// Compute the difference between two Modified Julian Dates in days (mjd1 − mjd2).
 double tempoch_mjd_difference(double mjd1, double mjd2);

// Add a duration in days to a Modified Julian Date.
 double tempoch_mjd_add_days(double mjd, double days);

// Compute Julian centuries since J2000 for a given Julian Date.
 double tempoch_jd_julian_centuries(double jd);

// Compute the difference between two Julian Dates as a `QttyQuantity` in days.
 qtty_quantity_t tempoch_jd_difference_qty(double jd1, double jd2);

// Add a `QttyQuantity` duration (time-compatible) to a Julian Date.
//
// Returns `InvalidDurationUnit` if the quantity cannot be converted to days.
//
// # Safety
// `out` must be a valid, writable pointer to `double`.
 tempoch_status_t tempoch_jd_add_qty(double jd, qtty_quantity_t duration, double *out);

// Compute the difference between two Modified Julian Dates as a `QttyQuantity` in days.
 qtty_quantity_t tempoch_mjd_difference_qty(double mjd1, double mjd2);

// Add a `QttyQuantity` duration (time-compatible) to a Modified Julian Date.
//
// Returns `InvalidDurationUnit` if the quantity cannot be converted to days.
//
// # Safety
// `out` must be a valid, writable pointer to `double`.
 tempoch_status_t tempoch_mjd_add_qty(double mjd, qtty_quantity_t duration, double *out);

// Compute Julian centuries since J2000 as a `QttyQuantity`.
 qtty_quantity_t tempoch_jd_julian_centuries_qty(double jd);

// Convert a Julian Date (TT) to TDB.
 double tempoch_jd_to_tdb(double jd);

// Convert TDB back to Julian Date (TT).
 double tempoch_tdb_to_jd(double tdb);

// Convert a Julian Date (TT) to TT (identity).
 double tempoch_jd_to_tt(double jd);

// Convert TT back to Julian Date (TT).
 double tempoch_tt_to_jd(double tt);

// Convert a Julian Date (TT) to TAI.
 double tempoch_jd_to_tai(double jd);

// Convert TAI back to Julian Date (TT).
 double tempoch_tai_to_jd(double tai);

// Convert a Julian Date (TT) to TCG.
 double tempoch_jd_to_tcg(double jd);

// Convert TCG back to Julian Date (TT).
 double tempoch_tcg_to_jd(double tcg);

// Convert a Julian Date (TT) to TCB.
 double tempoch_jd_to_tcb(double jd);

// Convert TCB back to Julian Date (TT).
 double tempoch_tcb_to_jd(double tcb);

// Convert a Julian Date (TT) to GPS Time.
 double tempoch_jd_to_gps(double jd);

// Convert GPS Time back to Julian Date (TT).
 double tempoch_gps_to_jd(double gps);

// Convert a Julian Date (TT) to Universal Time UT1.
 double tempoch_jd_to_ut(double jd);

// Convert Universal Time UT1 back to Julian Date (TT).
 double tempoch_ut_to_jd(double ut);

// Convert a Julian Date (TT) to Julian Ephemeris Date.
 double tempoch_jd_to_jde(double jd);

// Convert Julian Ephemeris Date back to Julian Date (TT).
 double tempoch_jde_to_jd(double jde);

// Convert a Julian Date (TT) to Unix time in **seconds** since 1970-01-01T00:00:00 UTC.
//
// The result is a standard Unix timestamp suitable for passing to C `gmtime()`,
// Python `datetime.fromtimestamp()`, etc. Internally the conversion routes
// through the compiled UTC-TAI history.
//
// Returns `NaN` if `jd` is non-finite or cannot be represented by the
// compiled UTC civil-time model.
 double tempoch_jd_to_unix(double jd);

// Convert Unix time in **seconds** since 1970-01-01T00:00:00 UTC back to Julian Date (TT).
//
// Accepts a standard Unix timestamp (seconds, not days). The conversion
// uses the compiled UTC-TAI history for leap-second handling.
//
// Returns `NaN` if `unix` is non-finite or outside the supported UTC civil range.
 double tempoch_unix_to_jd(double unix);

// Create a Unix timestamp from seconds since 1970-01-01T00:00:00 UTC.
//
// This is a convenience identity for the C ABI: the returned `double` is
// the same value, confirming that the FFI Unix convention is **seconds**.
// Use [`tempoch_unix_to_jd`] when you need the corresponding Julian Date.
 double tempoch_unix_from_seconds(double seconds);

// Extract the Unix timestamp in seconds from a value previously obtained
// via [`tempoch_jd_to_unix`] or [`tempoch_unix_from_seconds`].
//
// This is also a convenience identity confirming the seconds convention.
 double tempoch_unix_to_seconds(double unix);

// Return ΔT = TT − UT1 in seconds for a Julian Date.
//
// For dates within the compiled data range this is the observed/predicted
// value from USNO data. For dates beyond [`tempoch::DELTA_T_PREDICTION_HORIZON_MJD`]
// the result is a quadratic tail-fit extrapolation; accuracy degrades
// rapidly past the horizon. The value is never `NaN`; non-finite `jd`
// (infinity or NaN) returns `0.0`.
 double tempoch_delta_t_seconds(double jd);

// Convert a `double` time value from one scale to another.
//
// # Safety
// `out` must be a valid, writable pointer to `double`.

tempoch_status_t tempoch_time_convert(double value,
                                      int32_t from_scale_id,
                                      int32_t to_scale_id,
                                      double *out);

// Convert a UTC date-time to a value in any supported scale.
//
// # Safety
// `out` must be a valid, writable pointer to `double`.
 tempoch_status_t tempoch_time_from_utc(struct tempoch_utc_t utc, int32_t scale_id, double *out);

// Convert a time value in any supported scale to UTC.
//
// # Safety
// `out` must be a valid, writable pointer to `TempochUtc`.
 tempoch_status_t tempoch_time_to_utc(double value, int32_t scale_id, struct tempoch_utc_t *out);

// Compute a same-scale duration in days.
//
// # Safety
// `out` must be a valid, writable pointer to `double`.

tempoch_status_t tempoch_time_difference_days(double lhs,
                                              double rhs,
                                              int32_t scale_id,
                                              double *out);

// Compute a same-scale duration as a day-valued `QttyQuantity`.
//
// # Safety
// `out` must be a valid, writable pointer to `qtty_quantity_t`.

tempoch_status_t tempoch_time_difference_qty(double lhs,
                                             double rhs,
                                             int32_t scale_id,
                                             qtty_quantity_t *out);

// Add a same-scale duration in days.
//
// # Safety
// `out` must be a valid, writable pointer to `double`.
 tempoch_status_t tempoch_time_add_days(double value, int32_t scale_id, double days, double *out);

// Add a same-scale duration from a time-compatible `QttyQuantity`.
//
// # Safety
// `out` must be a valid, writable pointer to `double`.

tempoch_status_t tempoch_time_add_qty(double value,
                                      int32_t scale_id,
                                      qtty_quantity_t duration,
                                      double *out);

// Convert a Julian Date to any scale, writing the result into `out`.
//
// # Safety
// `out` must be a valid, writable pointer to `double`.
 tempoch_status_t tempoch_jd_to_scale(double jd, int32_t scale_id, double *out);

// Convert a value in any scale to a Julian Date, writing the result into `out`.
//
// # Safety
// `out` must be a valid, writable pointer to `double`.
 tempoch_status_t tempoch_scale_to_jd(double value, int32_t scale_id, double *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TEMPOCH_FFI_H */
