#ifndef TEMPOCH_FFI_H
#define TEMPOCH_FFI_H

/* Warning: this file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
/* QttyQuantity and UnitId definitions come from qtty_ffi.h */
#include "qtty_ffi.h"


// Status codes returned by tempoch-ffi functions.
//
enum tempoch_status_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  // Success.
  TEMPOCH_STATUS_T_OK = 0,
  // A required output pointer was null.
  TEMPOCH_STATUS_T_NULL_POINTER = 1,
  // UTC conversion failed (date out of range or invalid).
  TEMPOCH_STATUS_T_UTC_CONVERSION_FAILED = 2,
  // The period is invalid (start > end).
  TEMPOCH_STATUS_T_INVALID_PERIOD = 3,
  // The two periods do not intersect.
  TEMPOCH_STATUS_T_NO_INTERSECTION = 4,
};
#ifndef __cplusplus
typedef int32_t tempoch_status_t;
#endif // __cplusplus

// Scale label for the `tempoch_jd_to_scale()` / `tempoch_scale_to_jd()` dispatch.
//
enum TempochScale
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  TEMPOCH_SCALE_JD = 0,
  TEMPOCH_SCALE_MJD = 1,
  TEMPOCH_SCALE_TDB = 2,
  TEMPOCH_SCALE_TT = 3,
  TEMPOCH_SCALE_TAI = 4,
  TEMPOCH_SCALE_TCG = 5,
  TEMPOCH_SCALE_TCB = 6,
  TEMPOCH_SCALE_GPS = 7,
  TEMPOCH_SCALE_UT = 8,
  TEMPOCH_SCALE_JDE = 9,
  TEMPOCH_SCALE_UNIX_TIME = 10,
};
#ifndef __cplusplus
typedef int32_t TempochScale;
#endif // __cplusplus

// A time period in Modified Julian Date, suitable for C interop.
typedef struct tempoch_period_mjd_t {
  double start_mjd;
  double end_mjd;
} tempoch_period_mjd_t;

// UTC date-time breakdown for C interop.
typedef struct tempoch_utc_t {
  int32_t year;
  uint8_t month;
  uint8_t day;
  uint8_t hour;
  uint8_t minute;
  uint8_t second;
  uint32_t nanosecond;
} tempoch_utc_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the tempoch-ffi ABI version (semver-encoded: major*10000 + minor*100 + patch).
 uint32_t tempoch_ffi_version(void);

// Create a new MJD period. Returns InvalidPeriod if start > end.
//
// # Safety
// `out` must be a valid, writable pointer to `TempochPeriodMjd`.

tempoch_status_t tempoch_period_mjd_new(double start_mjd,
                                        double end_mjd,
                                        struct tempoch_period_mjd_t *out);

// Compute the duration of a period in days.
 double tempoch_period_mjd_duration_days(struct tempoch_period_mjd_t period);

// Compute the intersection of two periods.
// Returns NoIntersection if they don't overlap, Ok if `out` is filled.
//
// # Safety
// `out` must be a valid, writable pointer to `TempochPeriodMjd`.

tempoch_status_t tempoch_period_mjd_intersection(struct tempoch_period_mjd_t a,
                                                 struct tempoch_period_mjd_t b,
                                                 struct tempoch_period_mjd_t *out);

// Create a Julian Date from a raw f64 value.
 double tempoch_jd_new(double value);

// Return the J2000.0 epoch as a Julian Date (2451545.0).
 double tempoch_jd_j2000(void);

// Convert a Julian Date to a Modified Julian Date.
 double tempoch_jd_to_mjd(double jd);

// Create a Julian Date from a UTC date-time.
//
// # Safety
// `out` must be a valid, writable pointer to `f64`.
 tempoch_status_t tempoch_jd_from_utc(struct tempoch_utc_t utc, double *out);

// Convert a Julian Date to UTC. Returns Ok on success,
// UtcConversionFailed if the date is out of representable range.
//
// # Safety
// `out` must be a valid, writable pointer to `TempochUtc`.
 tempoch_status_t tempoch_jd_to_utc(double jd, struct tempoch_utc_t *out);

// Create a Modified Julian Date from a raw f64 value.
 double tempoch_mjd_new(double value);

// Convert a Modified Julian Date to a Julian Date.
 double tempoch_mjd_to_jd(double mjd);

// Create a Modified Julian Date from a UTC date-time.
//
// # Safety
// `out` must be a valid, writable pointer to `f64`.
 tempoch_status_t tempoch_mjd_from_utc(struct tempoch_utc_t utc, double *out);

// Convert a Modified Julian Date to UTC.
//
// # Safety
// `out` must be a valid, writable pointer to `TempochUtc`.
 tempoch_status_t tempoch_mjd_to_utc(double mjd, struct tempoch_utc_t *out);

// Compute the difference between two Julian Dates in days.
 double tempoch_jd_difference(double jd1, double jd2);

// Add a duration in days to a Julian Date.
 double tempoch_jd_add_days(double jd, double days);

// Compute the difference between two Modified Julian Dates in days.
 double tempoch_mjd_difference(double mjd1, double mjd2);

// Add a duration in days to a Modified Julian Date.
 double tempoch_mjd_add_days(double mjd, double days);

// Compute Julian centuries since J2000 for a given Julian Date.
 double tempoch_jd_julian_centuries(double jd);

// Compute the difference between two Julian Dates as a `QttyQuantity` in days.
 qtty_quantity_t tempoch_jd_difference_qty(double jd1, double jd2);

// Add a `QttyQuantity` duration (must be time-compatible) to a Julian Date.
// The quantity is converted to days internally.
//
// # Safety
// `out` must be a valid, writable pointer to `f64`.
 tempoch_status_t tempoch_jd_add_qty(double jd, qtty_quantity_t duration, double *out);

// Compute the difference between two Modified Julian Dates as a `QttyQuantity` in days.
 qtty_quantity_t tempoch_mjd_difference_qty(double mjd1, double mjd2);

// Add a `QttyQuantity` duration (must be time-compatible) to a Modified Julian Date.
// The quantity is converted to days internally.
//
// # Safety
// `out` must be a valid, writable pointer to `f64`.
 tempoch_status_t tempoch_mjd_add_qty(double mjd, qtty_quantity_t duration, double *out);

// Compute Julian centuries since J2000 as a `QttyQuantity`.
 qtty_quantity_t tempoch_jd_julian_centuries_qty(double jd);

// Compute the duration of a period as a `QttyQuantity` in days.
 qtty_quantity_t tempoch_period_mjd_duration_qty(struct tempoch_period_mjd_t period);

// Convert a Julian Date (TT) to TDB (Barycentric Dynamical Time).
 double tempoch_jd_to_tdb(double jd);

// Convert TDB back to Julian Date (TT).
 double tempoch_tdb_to_jd(double tdb);

// Convert a Julian Date (TT) to TT (Terrestrial Time). Identity—included for completeness.
 double tempoch_jd_to_tt(double jd);

// Convert TT back to Julian Date (TT). Identity.
 double tempoch_tt_to_jd(double tt);

// Convert a Julian Date (TT) to TAI (International Atomic Time).
 double tempoch_jd_to_tai(double jd);

// Convert TAI back to Julian Date (TT).
 double tempoch_tai_to_jd(double tai);

// Convert a Julian Date (TT) to TCG (Geocentric Coordinate Time).
 double tempoch_jd_to_tcg(double jd);

// Convert TCG back to Julian Date (TT).
 double tempoch_tcg_to_jd(double tcg);

// Convert a Julian Date (TT) to TCB (Barycentric Coordinate Time).
 double tempoch_jd_to_tcb(double jd);

// Convert TCB back to Julian Date (TT).
 double tempoch_tcb_to_jd(double tcb);

// Convert a Julian Date (TT) to GPS Time.
 double tempoch_jd_to_gps(double jd);

// Convert GPS Time back to Julian Date (TT).
 double tempoch_gps_to_jd(double gps);

// Convert a Julian Date (TT) to UT (Universal Time UT1).
 double tempoch_jd_to_ut(double jd);

// Convert UT back to Julian Date (TT).
 double tempoch_ut_to_jd(double ut);

// Convert a Julian Date (TT) to JDE (Julian Ephemeris Day — semantic alias of JD(TT)).
 double tempoch_jd_to_jde(double jd);

// Convert JDE back to Julian Date (TT).
 double tempoch_jde_to_jd(double jde);

// Convert a Julian Date (TT) to Unix Time (seconds since 1970-01-01T00:00:00 UTC, ignoring leap seconds).

double tempoch_jd_to_unix(double jd);

// Convert Unix Time back to Julian Date (TT).
 double tempoch_unix_to_jd(double unix);

// Return ΔT = TT − UT1 in seconds for a given Julian Date.
//
// Uses the piecewise polynomial/tabular model from tempoch-core.
 double tempoch_delta_t_seconds(double jd);

// Generic JD → any scale dispatch.
//
// Returns the value in the target time scale. Prefer the individual functions
// (`tempoch_jd_to_tdb`, etc.) when the target scale is known at compile time.
 double tempoch_jd_to_scale(double jd, TempochScale scale);

// Generic any scale → JD dispatch.
 double tempoch_scale_to_jd(double value, TempochScale scale);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TEMPOCH_FFI_H */
